apiVersion: v1
kind: Service
metadata:
  # Unique key of the Service instance
  name: service-my-node-app
spec:
  ports:
    # Accept traffic sent to port 80
    - name: http
      port: 8080
      targetPort: 3000
  selector:
    # Loadbalance traffic across Pods matching
    # this label selector
    app: node-app
  # Create an HA proxy in the cloud provider
  # with an External IP address - *Only supported
  # by some cloud providers*
  type: LoadBalancer